FROM ruby:3.1.1

ENV LANG=C.UTF-8 \
  TZ=Asia/Tokyo

RUN apt-get update -qq \
  && apt-get install -y nodejs default-mysql-client npm \
  && rm -rf /var/lib/apt/lists/* \
  && npm install --global yarn
WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN gem update --system
RUN bundle update --bundler
RUN bundle install

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0"]
